simulation:
  delta_t: 0.01
  total_hours: 12.0
  domain_length: 10.0
  dx_interval: 0.001
  diffusivity: 0.00026361376409494525
  m_diffusivity: 2e-3
  tau_m: 6.242153148113385
  flow: 0.19627128512102468
  activity: 0.8749997229064099
  beta: 0.9969669403539715
  gamma: 0.538795096984612
  sigma_c: 0.1
  r: 0.968870632027848
  rho_sensitivity: 0.0
  m_sensitivity: 0.05070302382000081
  morphogen_feedback: 1.2337528178981996
  feedback_mode: active_stress