# Model configuration
simulation:
  delta_t: 0.1  # time step (t_g units)
  total_hours: 12.0  # simulated biological time [h]
  domain_length: 10.0  # physical domain size (x ∈ [−L/2, L/2])
  dx_interval: 0.005 # IntervalMesh spacing
  diffusivity: 1e-3 # δ diffusivity
  tau_m: 6e0  # mesoderm growth timescale
  length_scale: 1.0  # L_0
  flow: 3e-1  # F, advection or flow
  activity: 1.15e0  # A
  beta: 0.45  # β contribution of mesoderm fate to cell's contractility
  gamma: 1e-2  # Γ friction coefficient
  sigma_c: 0.0  # σ_c (critical stress)
  r: 1e0  # r sensitivity of cells to mechanical feedback
  rho_sensitivity: 0.01  # sensitivity to ensure stress vanishes on the boundary of the tissue
  m_sensitivity: 0.01  # sensitivity of the step function that increases contractility of cells expressing mesoderm
  feedback_mode: strain_rate  # strain_rate or active_stress

# Optimization configuration
cma:
  x0:  # init
    diffusivity: 0.0061
    tau_m: 7.019
    length_scale: 1.377
    flow: 0.2155
    activity: 0.3061
    beta: 0.895
    gamma: 0.007973
    sigma_c: 0.2835
    r: 1.427
  
  sigma0: 0.15
  max_evals: 9000
  popsize: 16
  n_restarts: 8
  
  bounds:
    lower:
      diffusivity: 1e-4
      tau_m: 1.0
      length_scale: 0.2
      flow: 0.005
      activity: 0.1
      beta: 0.0
      gamma: 0.001
      sigma_c: 0.0
      r: 0.1
    
    upper:
      diffusivity: 5e-2
      tau_m: 24.0
      length_scale: 4.0
      flow: 2.0
      activity: 3.0
      beta: 1.5
      gamma: 0.1
      sigma_c: 5.0
      r: 10.0
