# Model configuration
simulation:
  delta_t: 0.01  # time step (t_g units) & must be < the tau_m lower bound (the fastest time-scale)
  total_hours: 12.0  # simulated biological time [h]
  domain_length: 10.0  # physical domain length (x ∈ [−L/2, L/2]) in nondim units
  dx_interval: 0.001 # IntervalMesh spacing
  diffusivity: 1e-3 # δ nondim diffusivity
  m_diffusivity: 1e-3 # artificial diffusivity on mesoderm for numerical stability
  tau_m: 6e0  # mesoderm growth timescale
  length_scale: 1.0  # No need for this anymore since the dimensionless length scale is always 1.0 (can be hard-coded into the intitial conditions acceptibly) 
  flow: 3e-1  # F, nondim advection or flow
  activity: 1.15e0  # nondim activity parameter A
  beta: 0.45  # β contribution of mesoderm fate to cell's contractility
  gamma: 1e-2  # Γ non friction coefficient
  sigma_c: 0.0  # σ_c (critical amount of mechanical feedback)
  r: 1e0  # r sensitivity of cells to mechanical feedback
  rho_sensitivity: 0.0  # saturation of active stress at high density
  m_sensitivity: 0.01  # sensitivity of the step function that increases contractility of cells expressing mesoderm
  feedback_mode: strain_rate  # strain_rate or active_stress

# Optimization configuration
cma:
  x0:  # init
    diffusivity: 0.07
    tau_m: 0.8
    flow: 1.5
    activity: 3.8
    beta: 1.8
    gamma: 0.3
    sigma_c: 0.5
    r: 3
    rho_sensitivity: 0.0
    m_sensitivity: 0.4
  
  sigma0: 0.15
  max_evals: 5000
  popsize: 24
  n_restarts: 8
  
  bounds:
    lower:
      diffusivity: 1e-5
      tau_m: 0.1
      flow: 0.0
      activity: 0.0
      beta: 0.0
      gamma: 1e-4
      sigma_c: 0.0
      r: 0.0
      rho_sensitivity: 0
      m_sensitivity: 1e-3
    
    upper:
      diffusivity: 1e-2
      tau_m: 8.0
      flow: 10.0
      activity: 5.0
      beta: 5.0
      gamma: 1
      sigma_c: 0.0
      r: 20.0
      rho_sensitivity: 0
      m_sensitivity: 1e-1
