cma:
  x0: 
    diffusivity: 8.980959167540726e-05
    tau_m: 7.0
    flow: 0.3
    activity: 0.8177242457000748
    beta: 0.6359440258892959
    gamma: 0.19664898263383435
    r: 1.4355095309012016
    m_sensitivity: 0.09628726199197271
    growth_inhibition: 2.5
  
  sigma0: 0.15
  max_evals: 4000
  popsize: 36
  n_restarts: 4
  tolstagnation: 8
  
  bounds:
    lower:
      diffusivity: 1e-5
      tau_m: 0.1
      flow: 0.0
      activity: 0.0
      beta: 0.0
      gamma: 1e-4
      r: 0.0
      m_sensitivity: 1e-3
      growth_inhibition: 0.0
    
    upper:
      diffusivity: 1e-2
      tau_m: 8.0
      flow: 10.0
      activity: 5.0
      beta: 5.0
      gamma: 1
      r: 20.0
      m_sensitivity: 1e-1
      growth_inhibition: 5.0